--CREATING DATABASE 
CREATE DATABASE EMPLOYEE_DB2;

--USING CREATED DATABASE
USE EMPLOYEE_DB2;

--TABLE 1 (PRIMARY TABLE)
CREATE TABLE EMPLOYEE_DETAILS(
		EMP_ID INT IDENTITY(101,1),
		EMP_CODE VARCHAR(10) NOT NULL UNIQUE,
		EMP_NAME VARCHAR(20) DEFAULT('Prolifics'),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP,
		PRIMARY KEY(EMP_CODE, EMP_NAME)
);


--TABLE 2
CREATE TABLE ACCOUNT(
		ACC_ID INT IDENTITY(10001,1) PRIMARY KEY,
		EMP_CODE VARCHAR(10),
		EMP_NAME VARCHAR(20) DEFAULT('Prolifics'),
		ACC_NO BIGINT,
		ACC_IFSC VARCHAR(12),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP,
		CONSTRAINT LINK_TO_ACCOUNT FOREIGN KEY(EMP_CODE, EMP_NAME) REFERENCES EMPLOYEE_DETAILS(EMP_CODE, EMP_NAME)
);

-- TABLE 3
CREATE TABLE SALARY(
		SALARY_ID INT IDENTITY(1001,1) PRIMARY KEY,
		ACC_ID INT FOREIGN KEY REFERENCES ACCOUNT (ACC_ID),
		EMP_CODE VARCHAR(10) ,
		EMP_NAME VARCHAR(20) DEFAULT('Prolifics'),
		SAL_AMT MONEY DEFAULT(0),
		MONTH_SALARIED VARCHAR(5),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP,
		CONSTRAINT LINK_TO_SALARY FOREIGN KEY(EMP_CODE, EMP_NAME) REFERENCES EMPLOYEE_DETAILS(EMP_CODE, EMP_NAME)
);

--TABLE DESCRIPTION
EXEC SP_COLUMNS EMPLOYEE_DETAILS;
EXEC SP_COLUMNS ACCOUNT;
EXEC SP_COLUMNS SALARY;

/*
DROP TABLE SALARY;
DROP TABLE ACCOUNT;
DROP TABLE EMPLOYEE_DETAILS;
*/



SELECT * FROM EMPLOYEE_DETAILS;
SELECT * FROM SALARY;
SELECT * FROM ACCOUNT;