
--CREATING DATABASE 
CREATE DATABASE EMPLOYEE_DB;

--USING CREATED DATABASE
USE EMPLOYEE_DB;

--TABLE 1 (PRIMARY TABLE)
CREATE TABLE EMPLOYEE_DETAILS(
		EMP_ID INT IDENTITY(101,1) PRIMARY KEY,
		EMP_NAME VARCHAR(20),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP
);

--TABLE 2
CREATE TABLE ATTENDANCE(
		ATT_ID INT IDENTITY(1,1) PRIMARY KEY,
		EMP_ID INT FOREIGN KEY REFERENCES EMPLOYEE_DETAILS(EMP_ID),
		TIME_IN DATETIME,
		TIME_OUT DATETIME,
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP
);

--TABLE 3
CREATE TABLE ACCOUNT(
		ACC_ID INT IDENTITY(10001,1) PRIMARY KEY,
		EMP_ID INT FOREIGN KEY REFERENCES EMPLOYEE_DETAILS(EMP_ID),
		ACC_NO BIGINT,
		ACC_IFSC VARCHAR(12),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP
);

-- TABLE 3
CREATE TABLE SALARY(
		SALARY_ID INT IDENTITY(1001,1) PRIMARY KEY,
		ACC_ID INT FOREIGN KEY REFERENCES ACCOUNT (ACC_ID),
		SAL_AMT MONEY,
		MONTH_SALARIED VARCHAR(5),
		RECORD_CREATED_ON DATETIMEOFFSET,
		ROWVERSION TIMESTAMP
);

--TABLE DESCRIPTION
EXEC SP_COLUMNS EMPLOYEE_DETAILS;
EXEC SP_COLUMNS ACCOUNT;
EXEC SP_COLUMNS ATTENDANCE;
EXEC SP_COLUMNS SALARY;

INSERT INTO ATTENDANCE(EMP_ID, TIME_IN, TIME_OUT, RECORD_CREATED_ON) VALUES
	(105, '2023-01-01 09:00:00',  '2023-01-01 06:00:00', SYSDATETIMEOFFSET());


SELECT * FROM EMPLOYEE_DETAILS;
SELECT * FROM SALARY;
SELECT * FROM ACCOUNT;
SELECT * FROM ATTENDANCE;